# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll for Web Designers
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/jekyll-for-designers"
url: "http://viv-b.github.io/jekyll-for-designers"
tagline: "A basic guide to Jekyll"

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]
theme: minima
permalink: /blog/:title
